### ISSUE TITLE
Execution failed for task

### ISSUE THREAD

**Issue by jjsebastianfuertes** [ayyshim/google_map_polyutil#1]
When I try flutter run I get this error:

Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'com.android.builder.files.ZipCentralDirectory@40a957b9' was deleted, but previous version not found in cache

**Comment by ayyshim** [comment]
Try `flutter clean` command and then `flutter run`
